# Deep Learning A Z Classificação binária - Brest Cancer simples

- Base de dados: https://archive.ics.uci.edu/dataset/17/breast+cancer+wisconsin+diagnostic

In [1]:
import pandas as pd

In [2]:
pd.__version__

'2.2.2'

In [3]:
# previsores
X = pd.read_csv('entradas_breast.csv')
X

radius_mean   texture_mean   perimeter_mean   area_mean  \
0           17.99          10.38           122.80      1001.0   
1           20.57          17.77           132.90      1326.0   
2           19.69          21.25           130.00      1203.0   
3           11.42          20.38            77.58       386.1   
4           20.29          14.34           135.10      1297.0   
..            ...            ...              ...         ...   
564         21.56          22.39           142.00      1479.0   
565         20.13          28.25           131.20      1261.0   
566         16.60          28.08           108.30       858.1   
567         20.60          29.33           140.10      1265.0   
568          7.76          24.54            47.92       181.0   

      smoothness_mean   compactness_mean   concavity_mean  \
0             0.11840            0.27760          0.30010   
1             0.08474            0.07864          0.08690   
2             0.10960            0.15990          0.19740   
3             0.14250            0.28390          0.24140   
4             0.10030            0.13280        198.00000   
..                ...                ...              ...   
564         111.00000            0.11590          0.24390   
565           0.09780            0.10340        144.00000   
566           0.08455            0.10230          0.09251   
567           0.11780          277.00000          0.35140   
568           0.05263            0.04362          0.00000   

     concave_points_mean   symmetry_mean   fractal_dimension_mean  ...  \
0                0.14710          0.2419                  0.07871  ...   
1                0.07017          0.1812                  0.05667  ...   
2                0.12790          0.2069                  0.05999  ...   
3                0.10520          0.2597                  0.09744  ...   
4                0.10430          0.1809                  0.05883  ...   
..                   ...             ...                      ...  ...   
564              0.13890          0.1726                  0.05623  ...   
565              0.09791          0.1752                  0.05533  ...   
566              0.05302        159.0000                  0.05648  ...   
567            152.00000          0.2397                  0.07016  ...   
568              0.00000          0.1587                  0.05884  ...   

      radius_worst   texture_worst   perimeter_worst   area_worst  \
0            25.38           17.33            184.60       2019.0   
1            24.99           23.41            158.80       1956.0   
2            23.57           25.53            152.50       1709.0   
3            14.91           26.50             98.87        567.7   
4            22.54           16.67            152.20       1575.0   
..             ...             ...               ...          ...   
564          25.45           26.40            166.10       2027.0   
565          23.69           38.25            155.00       1731.0   
566          18.98           34.12            126.70       1124.0   
567          25.74           39.42            184.60       1821.0   
568        9456.00           30.37             59.16        268.6   

      smoothness_worst   compactness_worst   concavity_worst  \
0              0.16220             0.66560            0.7119   
1              0.12380             0.18660            0.2416   
2              0.14440             0.42450            0.4504   
3              0.20980             0.86630            0.6869   
4              0.13740           205.00000            0.4000   
..                 ...                 ...               ...   
564          141.00000             0.21130            0.4107   
565            0.11660             0.19220            0.3215   
566            0.11390             0.30940            0.3403   
567          165.00000             0.86810            0.9387   
568            0.08996             0.06444            0.0000   

     

In [4]:
# classe
y = pd.read_csv('saidas_breast.csv')
y

0
0    0
1    0
2    0
3    0
4    0
..  ..
564  0
565  0
566  0
567  0
568  1

[569 rows x 1 columns]

In [5]:
import sklearn
from sklearn.model_selection import train_test_split

In [6]:
sklearn.__version__

'1.5.1'

In [7]:
# X_treinamento = previsores de treinamento (que são as características dos tumores)
# X_teste = previsores de teste
# y_treinamento = classe de treinamento (que são os resultados dos tumores)
# y_teste = classe de teste
X_treinamento, X_teste, y_treinamento, y_teste = train_test_split(X, y, test_size=0.25) # 25% para teste

In [8]:
X_treinamento.shape, y_treinamento.shape # 426 registros para treinamento

((426, 30), (426, 1))

In [9]:
X_teste.shape, y_teste.shape # 143 registros para teste

((143, 30), (143, 1))

In [ ]:
#!pip install tensorflow==2.16.1

In [10]:
import tensorflow as tf
from tensorflow.keras.models import Sequential

In [11]:
tf.__version__

'2.17.0'

In [12]:
# Criação da estrutura da rede neural
rede_neural = Sequential([
    tf.keras.layers.InputLayer(shape = (30,)), # Camada de entrada com 30 neurônios (características)
    tf.keras.layers.Dense(units = 16, activation = 'relu', kernel_initializer = 'random_uniform'), # Camada oculta com 16 neurônios 
    # (número de neurônios da camada oculta é a média entre a quantidade de neurônios da camada de entrada e da camada de saída (30+1)/2 = 16)
    tf.keras.layers.Dense(units = 1, activation = 'sigmoid') # Camada de saída com 1 neurônio (resultado binário)
])

In [20]:
30 * 16, 496 - 480 # Bias

(480, 16)

In [21]:
496 + 17

513

In [13]:
rede_neural.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 16)             │           496 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │            17 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 513 (2.00 KB)

 Trainable params: 513 (2.00 KB)

 Non-trainable params: 0 (0.00 B)

In [14]:
rede_neural.compile(optimizer = 'adam', # Algoritmo de ajuste dos pesos
                    loss = 'binary_crossentropy', # Função de erro
                    metrics = ['binary_accuracy']) # Métrica de avaliação (binária)

In [24]:
426 / 10

42.6

In [15]:
rede_neural.fit(X_treinamento, y_treinamento, batch_size = 10, epochs = 100) 
# Definição do tamanho do batch sendo 10, ou seja, a cada 10 registros a rede neural fará o ajuste dos pesos
# Total de 42 batchs criados (426 / 10 = 42)

Epoch 1/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - binary_accuracy: 0.4990 - loss: 17.7261
Epoch 2/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.7156 - loss: 2.1332
Epoch 3/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.7617 - loss: 1.1355
Epoch 4/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8113 - loss: 0.6328
Epoch 5/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8444 - loss: 0.6641
Epoch 6/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8433 - loss: 0.5904
Epoch 7/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8576 - loss: 0.5547  
Epoch 8/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.7921 - loss: 1.1426  
Epoch 9/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8920 - loss: 0.3958
Epoch 10/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8805 - loss: 0.4696 
Epoch 11/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.

In [ ]:
previsoes = rede_neural.predict(X_teste) # Previsões da rede neural
previsoes = previsoes > 0.5 # Transformação das previsões em valores binários (True ou False)

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step 


In [19]:
previsoes

array([[False],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [

In [20]:
y_teste

0
54   0
114  1
103  1
130  1
557  1
..  ..
157  1
341  1
17   0
338  1
175  1

[143 rows x 1 columns]

In [21]:
from sklearn.metrics import confusion_matrix, accuracy_score

In [23]:
accuracy_score(y_teste, # Resultado real 
               previsoes # Resultado previsto
               )

0.8111888111888111

In [24]:
confusion_matrix(y_teste, # Resultado real
                 previsoes # Resultado previsto
                 )

array([[46,  6],
       [21, 70]], dtype=int64)

In [ ]:
# array([[46,  6],
#        [21, 70]]
# A rede neural acertou 46 tumores benignos e 70 tumores malignos
# A rede neural errou 21 tumores malignos (classificando-os como benignos) e 6 tumores benignos (classificando-os como malignos)

In [25]:
rede_neural.evaluate(X_teste, y_teste) # Avaliação da rede neural 

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.8138 - loss: 0.6620  


[0.6461389660835266, 0.811188817024231]

# Adicionando mais camadas na estrura da rede e parâmtros no otimizador

In [26]:
# Criação da estrutura da rede neural
rede_neural = Sequential([
    tf.keras.layers.InputLayer(shape = (30,)), # Camada de entrada com 30 neurônios (características)
    tf.keras.layers.Dense(units = 16, activation = 'relu', kernel_initializer = 'random_uniform'), # Camada oculta com 16 neurônios 
    # (número de neurônios da camada oculta é a média entre a quantidade de neurônios da camada de entrada e da camada de saída (30+1)/2 = 16)
    tf.keras.layers.Dense(units = 16, activation = 'relu', kernel_initializer = 'random_uniform'), # Camada oculta com 16 neurônios
    tf.keras.layers.Dense(units = 1, activation = 'sigmoid') # Camada de saída com 1 neurônio (resultado binário)
])

In [27]:
rede_neural.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_2 (Dense)                 │ (None, 16)             │           496 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 16)             │           272 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 1)              │            17 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 785 (3.07 KB)

 Trainable params: 785 (3.07 KB)

 Non-trainable params: 0 (0.00 B)

In [28]:
otimizador = tf.keras.optimizers.Adam(learning_rate = 0.001, # Taxa de aprendizagem 
                                      clipvalue = 0.5 # Valor máximo para o ajuste dos pesos
                                      )

In [29]:
rede_neural.compile(optimizer = otimizador, loss = 'binary_crossentropy', metrics = ['binary_accuracy']) 
# Agora, ao invés de passar o Adam, passamos o otimizador criado

In [30]:
rede_neural.fit(X_treinamento, y_treinamento, batch_size = 10, epochs = 100) # Treinamento da rede neural mais densa e com otimizador

Epoch 1/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - binary_accuracy: 0.6398 - loss: 0.7713
Epoch 2/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.7848 - loss: 0.4913 
Epoch 3/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8534 - loss: 0.4173
Epoch 4/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.7804 - loss: 0.5137  
Epoch 5/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8760 - loss: 0.3443
Epoch 6/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8614 - loss: 0.4361
Epoch 7/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8779 - loss: 0.4748
Epoch 8/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8265 - loss: 1.6030   
Epoch 9/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - binary_accuracy: 0.8331 - loss: 0.7265
Epoch 10/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8730 - loss: 0.3782
Epoch 11/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.

In [31]:
rede_neural.evaluate(X_teste, y_teste) # Avaliação da rede neural
# O valor do erro aumentou, mas a acurácia aumentou também

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - binary_accuracy: 0.8489 - loss: 1.12074


[1.1578515768051147, 0.867132842540741]

In [32]:
pesos0 = rede_neural.layers[0].get_weights()
pesos0

[array([[ 1.88666210e-01,  1.01926088e-01, -4.20876965e-02,
         -1.43491089e-01, -8.35787803e-02, -2.34242268e-02,
         -5.09550691e-01,  3.62966269e-01, -1.29156671e-02,
          2.00462803e-01,  7.90347531e-02, -3.75286937e-02,
         -6.17772974e-02,  2.31462363e-02,  2.38884330e-01,
          7.83751383e-02],
        [ 1.89903341e-02,  1.66881949e-01, -1.99028645e-02,
         -1.34040982e-01,  1.31845519e-01,  7.29406402e-02,
         -4.05712306e-01,  5.21417797e-01, -1.55265406e-01,
          1.59206584e-01,  2.54576832e-01, -2.32506424e-01,
          1.41332269e-01,  1.32541382e-03,  3.36568803e-01,
          1.58937983e-02],
        [ 5.00153564e-02, -2.71433573e-02,  3.69581045e-03,
          9.75640863e-02,  1.65591091e-01, -1.44089265e-02,
         -2.41693094e-01,  2.95043081e-01,  9.02904198e-02,
          1.47461459e-01,  1.14815772e-01,  1.09613575e-02,
          1.23753548e-01,  6.68846816e-02,  1.22735195e-01,
          2.98342528e-03],
        [-3.9402812

In [33]:
len(pesos0)

2

In [38]:
len(pesos0[1]), pesos0[1]

(16,
 array([-0.11709276, -0.33407766, -0.02212636,  0.33930814,  0.34608522,
        -0.48200315, -0.36753687,  0.46215987,  0.28272697, -0.01052921,
         0.19410262,  0.169714  ,  0.13332748,  0.01376531, -0.06041123,
        -0.01069255], dtype=float32))

In [41]:
len(pesos0[0])

30

In [42]:
pesos1 = rede_neural.layers[1].get_weights()
pesos1

[array([[-6.38839463e-03,  9.58014652e-02,  2.67328136e-02,
          7.18953758e-02,  2.45934492e-03,  1.44372910e-01,
         -7.18679354e-02,  1.15034245e-01,  2.05932651e-02,
         -5.57395518e-02, -1.29347667e-02, -5.34729958e-02,
          3.38440537e-02, -1.04624638e-02, -8.28081369e-02,
         -4.61999550e-02],
        [-3.97526771e-02,  6.00324757e-02, -2.43672356e-02,
          1.27585620e-01, -1.00186095e-02,  1.68055698e-01,
         -1.35977164e-01,  1.15089990e-01,  5.23081869e-02,
         -1.19849548e-01, -3.79956886e-03,  1.34348264e-02,
         -2.28381567e-02, -1.35763707e-02, -1.65935997e-02,
         -5.93142658e-02],
        [-1.03434175e-03, -3.10191754e-02,  3.74075882e-02,
         -1.93327591e-02,  5.38533255e-02,  5.49431778e-02,
          3.24641392e-02,  1.95364282e-02,  2.41771974e-02,
          1.30144395e-02,  2.30023600e-02,  1.88594256e-02,
          1.98612791e-02, -1.95542313e-02, -5.90228811e-02,
          5.13692107e-03],
        [ 1.6131125

In [43]:
pesos2 = rede_neural.layers[2].get_weights()
pesos2

[array([[-0.10888097],
        [-0.32483786],
        [-0.28937483],
        [ 0.3489707 ],
        [-0.21076006],
        [-0.18223885],
        [ 0.30444902],
        [-0.74736977],
        [ 0.32652956],
        [ 0.23164266],
        [-0.0147047 ],
        [ 0.5463801 ],
        [ 0.0647077 ],
        [-0.4842192 ],
        [ 0.25260985],
        [-0.42213663]], dtype=float32),
 array([0.1618361], dtype=float32)]