# Deep Learning A Z Classificação Mais Classes - Iris simples

In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf
import sklearn

In [2]:
pd.__version__, np.__version__, tf.__version__, sklearn.__version__

('2.2.2', '1.26.4', '2.17.0', '1.5.1')

In [3]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras import utils as np_utils
from sklearn.preprocessing import LabelEncoder # Será usado para transformar as labels em números
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix

In [4]:
base = pd.read_csv('iris.csv')
base

sepal length  sepal width  petal length  petal width           class
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [5]:
X = base.iloc[:, 0:4].values # Atributos previsores, 150 linhas e 4 colunas
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [6]:
y = base.iloc[:, 4].values # Atributos classe, 150 linhas e 1 coluna
y

array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versic

In [7]:
label_encoder = LabelEncoder()
y = label_encoder.fit_transform(y) # Transforma as labels em números
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [10]:
y.shape

(150, 3)

In [9]:
y = np_utils.to_categorical(y) # Transforma os valores de y em categorias 
# (1, 0, 0 indica a classe da Iris-setosa, 0, 1, 0 indica a classe da Iris-versicolor e 0, 0, 1 indica a classe da Iris-virginica)
y

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [11]:
X_treinamento, X_teste, y_treinamento, y_teste = train_test_split(X, y, test_size=0.25)

In [12]:
X_treinamento.shape, X_teste.shape

((112, 4), (38, 4))

In [13]:
y_treinamento.shape, y_teste.shape

((112, 3), (38, 3))

In [17]:
(4 + 3) / 2
# (Numero de atributos (features) + Numero de classes (resultado)) / 2 = 3.5

3.5

In [14]:
rede_neural = Sequential([
    tf.keras.layers.InputLayer(shape = (4,)), # Camada de entrada com 4 neurônios (4 atributos)
    tf.keras.layers.Dense(units = 4, activation = 'relu'),
    tf.keras.layers.Dense(units = 4, activation = 'relu'),
    tf.keras.layers.Dense(units = 3, activation = 'softmax') # Note que aqui utilzamos a função de ativação softmax, por conta de ser um problema de classificação com mais de duas classes
])

In [15]:
rede_neural.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 4)              │            20 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 4)              │            20 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 3)              │            15 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 55 (220.00 B)

 Trainable params: 55 (220.00 B)

 Non-trainable params: 0 (0.00 B)

In [17]:
rede_neural.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['categorical_accuracy'])
# Função de perda e métricas para problemas de classificação com mais de duas classes

In [18]:
rede_neural.fit(X_treinamento, y_treinamento, batch_size = 10, epochs = 1000)

Epoch 1/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - categorical_accuracy: 0.2328 - loss: 2.1680 
Epoch 2/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - categorical_accuracy: 0.2409 - loss: 1.9435
Epoch 3/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - categorical_accuracy: 0.2433 - loss: 1.7175
Epoch 4/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - categorical_accuracy: 0.2892 - loss: 1.4978  
Epoch 5/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - categorical_accuracy: 0.3120 - loss: 1.3779
Epoch 6/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - categorical_accuracy: 0.3446 - loss: 1.2182
Epoch 7/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - categorical_accuracy: 0.3215 - loss: 1.2255
Epoch 8/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.3028 - loss: 1.1704
Epoch 9/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - categorical_accuracy: 0.2665 - loss: 1.2231 
Epoch 10/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - categorical_accuracy: 0.2841 - loss: 1.1195
Epoch 11/1000
1

In [ ]:
rede_neural.evaluate(X_teste, y_teste) # Avalia o modelo com os dados de teste

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - categorical_accuracy: 0.9720 - loss: 0.0619


[0.06372760236263275, 0.9736841917037964]

In [ ]:
previsoes = rede_neural.predict(X_teste) # Faz as previsões com os dados de teste
print(previsoes)

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step
[[8.09687026e-06 9.97548640e-01 2.44329637e-03]
 [9.99993086e-01 5.90252785e-06 9.90976901e-07]
 [1.00000000e+00 5.44415846e-09 6.45586154e-11]
 [1.07737677e-03 2.00199541e-02 9.78902698e-01]
 [9.99969602e-01 2.75813945e-05 2.82479550e-06]
 [9.99999285e-01 6.81228357e-07 5.04309519e-08]
 [1.00000000e+00 4.75093636e-08 1.28114774e-09]
 [9.99999523e-01 4.72511772e-07 3.04484615e-08]
 [9.99999046e-01 8.89609964e-07 7.28716927e-08]
 [5.81498352e-06 9.98373508e-01 1.62063888e-03]
 [3.47348745e-04 7.47460544e-01 2.52192050e-01]
 [9.99999762e-01 1.90307460e-07 8.68617445e-09]
 [2.26797874e-06 9.99493361e-01 5.04334050e-04]
 [1.08042976e-03 2.24912353e-02 9.76428330e-01]
 [9.99999881e-01 1.72292232e-07 7.57286589e-09]
 [2.48917559e-06 9.99431431e-01 5.66007162e-04]
 [9.99993920e-01 5.84903046e-06 2.93814850e-07]
 [9.99998689e-01 1.20573509e-06 1.10838315e-07]
 [1.07737677e-03 2.00199541e-02 9.78902698e-01]
 [9.99999523e-01 4.37291277e-07 2.73630967e-08]
 [

In [21]:
previsoes = previsoes > 0.5
print(previsoes)

[[False  True False]
 [ True False False]
 [ True False False]
 [False False  True]
 [ True False False]
 [ True False False]
 [ True False False]
 [ True False False]
 [ True False False]
 [False  True False]
 [False  True False]
 [ True False False]
 [False  True False]
 [False False  True]
 [ True False False]
 [False  True False]
 [ True False False]
 [ True False False]
 [False False  True]
 [ True False False]
 [ True False False]
 [False False  True]
 [False False  True]
 [ True False False]
 [ True False False]
 [False False  True]
 [ True False False]
 [ True False False]
 [False False  True]
 [False  True False]
 [False  True False]
 [False  True False]
 [False False  True]
 [ True False False]
 [False False  True]
 [False False  True]
 [False  True False]
 [False  True False]]


In [ ]:
y_teste2 = [np.argmax(t) for t in y_teste] # Retorna o índice do valor True em cada linha
print(y_teste2)

[1, 0, 0, 2, 0, 0, 0, 0, 0, 1, 2, 0, 1, 2, 0, 1, 0, 0, 2, 0, 0, 2, 2, 0, 0, 2, 0, 0, 2, 1, 1, 1, 2, 0, 2, 2, 1, 1]


In [24]:
previsoes2 = [np.argmax(t) for t in previsoes]
print(previsoes2)

[1, 0, 0, 2, 0, 0, 0, 0, 0, 1, 1, 0, 1, 2, 0, 1, 0, 0, 2, 0, 0, 2, 2, 0, 0, 2, 0, 0, 2, 1, 1, 1, 2, 0, 2, 2, 1, 1]


In [25]:
from sklearn.metrics import accuracy_score

In [26]:
accuracy_score(y_teste2, previsoes2)

0.9736842105263158

In [ ]:
# 0 setosa, 1 versicolor, 2 virginica

In [27]:
confusion_matrix(y_teste2, previsoes2)
# Nesse caso, o modelo classificou incorretamente uma Iris-virginica como uma Iris-versicolor

array([[18,  0,  0],
       [ 0,  9,  0],
       [ 0,  1, 10]], dtype=int64)