In [1]:
import torch

In [2]:
x = torch.tensor([[1,2,3,4], [5,6,7,8]])
x.shape

torch.Size([2, 4])

In [3]:
x * 10

tensor([[10, 20, 30, 40],
        [50, 60, 70, 80]])

In [5]:
x.add(10)

tensor([[11, 12, 13, 14],
        [15, 16, 17, 18]])

# Reshaping

In [6]:
x

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])

In [7]:
x.shape

torch.Size([2, 4])

In [ ]:
x.view(4,2) # Quatro linhas, duas colunas

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])

In [9]:
x.view(8,1) # O mesmo tensor, mas com 8 linhas e 1 coluna

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8]])

In [ ]:
a = torch.ones(2,1,10) # Gera duas linhas (y), uma coluna (x) e 10 elementos "1" em cada
a

tensor([[[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]]])

In [17]:
a.shape
squeezed = a.squeeze(1) # Remove a dimensão 1 (a segunda dimensão)
print(f"Formato squeezed: {squeezed.shape}")
squeezed

Formato squeezed: torch.Size([2, 10])


tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [20]:
a = torch.ones(2,3)
print(a)
unsqueezed = a.unsqueeze(2) # Adiciona uma dimensão 2 (a terceira dimensão)
print(f"Formato unsqueezed: {unsqueezed.shape}")
unsqueezed

tensor([[1., 1., 1.],
        [1., 1., 1.]])
Formato unsqueezed: torch.Size([2, 3, 1])


tensor([[[1.],
         [1.],
         [1.]],

        [[1.],
         [1.],
         [1.]]])

# Indexação None

In [21]:
a = torch.ones(2,3)

In [22]:
print(a[None].shape) # Adiciona uma dimensão 0 (a primeira dimensão)
print(a[:, None, :].shape) # Adiciona uma dimensão 1 (a segunda dimensão)
print(a[:, :, None].shape) # Adiciona uma dimensão 2 (a terceira dimensão)

torch.Size([1, 2, 3])
torch.Size([2, 1, 3])
torch.Size([2, 3, 1])


# Multiplicação de Matrizes

In [24]:
x = torch.tensor([[1,2,3,4], [5,6,7,8]])
y = torch.tensor([[1,2,3],
                   [2,3,4],
                   [4,5,6],
                   [7,8,9]])

In [ ]:
torch.matmul(x,y)


tensor([[ 45,  55,  65],
        [101, 127, 153]])

# Concatenção

In [ ]:
x = torch.randn(1,4,5) # 1 batch, 4 linhas, 5 colunas
z = torch.cat((x,x), axis=1) # Concatena na dimensão 1 (linhas)
x.shape, z.shape

(torch.Size([1, 4, 5]), torch.Size([1, 8, 5]))

# Permute

In [ ]:
x = torch.randn(3,20,10)
z = x.permute(2,0,1) # Troca as dimensões de lugar
z.shape, x.shape
# Essa operação é útil para fazer operações de batch em redes neurais convolucionais, por exemplo.
# A operação "permute" troca as dimensões de lugar, mas não altera os dados.

(torch.Size([10, 3, 20]), torch.Size([3, 20, 10]))