In [1]:
import torch

In [10]:
x = torch.tensor([[10, 20, 30, 40],
                  [-25, 50, -75, -100],
                  [-20, 83, 58, 29]])
x.shape

torch.Size([3, 4])

In [18]:
x / 10 * 2 + 12

tensor([[14.0000, 16.0000, 18.0000, 20.0000],
        [ 7.0000, 22.0000, -3.0000, -8.0000],
        [ 8.0000, 28.6000, 23.6000, 17.8000]])

In [19]:
x.sub(10)

tensor([[   0,   10,   20,   30],
        [ -35,   40,  -85, -110],
        [ -30,   73,   48,   19]])

In [20]:
x

tensor([[  10,   20,   30,   40],
        [ -25,   50,  -75, -100],
        [ -20,   83,   58,   29]])

In [21]:
x.shape

torch.Size([3, 4])

In [25]:
x.view(12,1) # Quatro linhas, duas colunas

tensor([[  10],
        [  20],
        [  30],
        [  40],
        [ -25],
        [  50],
        [ -75],
        [-100],
        [ -20],
        [  83],
        [  58],
        [  29]])

In [27]:
x.view(2,3,2) # Duas linhas, três colunas, duas camadas

tensor([[[  10,   20],
         [  30,   40],
         [ -25,   50]],

        [[ -75, -100],
         [ -20,   83],
         [  58,   29]]])

In [62]:
a = torch.ones(4,2,5) # Gera um tensor de 4 linhas, 4 colunas e 5 camadas
a

tensor([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]])

# Indexação None

In [21]:
a = torch.ones(2,3)

In [22]:
print(a[None].shape) # Adiciona uma dimensão 0 (a primeira dimensão)
print(a[:, None, :].shape) # Adiciona uma dimensão 1 (a segunda dimensão)
print(a[:, :, None].shape) # Adiciona uma dimensão 2 (a terceira dimensão)

torch.Size([1, 2, 3])
torch.Size([2, 1, 3])
torch.Size([2, 3, 1])


# Multiplicação de Matrizes

In [ ]:
x = torch.tensor([[1,2,3,4], [5,6,7,8]])
y = torch.tensor([[1,2,3],
                   [2,3,4],
                   [4,5,6],
                   [7,8,9]])

In [ ]:
torch.matmul(x,y)

tensor([[ 45,  55,  65],
        [101, 127, 153]])

In [ ]:
x = torch.randn(1,4,5) # 1 batch, 4 linhas, 5 colunas
z = torch.cat((x,x), axis=1) # Concatena na dimensão 1 (linhas)
x.shape, z.shape

(torch.Size([1, 4, 5]), torch.Size([1, 8, 5]))

# Permute

In [ ]:
x = torch.randn(3,20,10)
z = x.permute(2,0,1) # Troca as dimensões de lugar
z.shape, x.shape
# Essa operação é útil para fazer operações de batch em redes neurais convolucionais, por exemplo.
# A operação "permute" troca as dimensões de lugar, mas não altera os dados.

(torch.Size([10, 3, 20]), torch.Size([3, 20, 10]))